version: "3.7"
services:
  ProjectZomboidDedicatedServer:
    image: danixu86/project-zomboid-dedicated-server:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - STEAMAPPBRANCH=${STEAMAPPBRANCH}
    env_file:
      - .env
    ports:
      - "16261-16262:16261-16262/udp"
      - "8766-8768:8766-8768/udp"
    volumes:
      - ./data:/home/steam/Zomboid
      - ./workshop-mods:/home/steam/pz-dedicated/steamapps/workshop