services:
  projectzomboid:
    image: docker.io/indifferentbroccoli/projectzomboid-server-docker:latest
    restart: unless-stopped
    container_name: projectzomboid
    stop_grace_period: 30s
    ports:
      - 8766:8766/udp
      - 8767:8767/udp
      - 8768:8768/tcp
    environment:
      GENERATE_SETTINGS: true
    env_file:
      - .env
    volumes:
      - ./server-files:/project-zomboid
      - ./server-data:/project-zomboid-config